backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
collections:
    - name: 'blog'
      label: 'Blog'
      folder: '_posts/'
      fields:
        - { name: Title }
    - name: "website-settings"
      label: "website settings"
      files:
        - label: "Business Info"
          name: "info"
          file: "_data/site.yml"
          fields:
            - { label: heading, name: heading, widget: string }


