backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
media_folder: 'images/uploads'
collections:
    - name: 'blog'
      label: 'Blog'
      folder: '_posts/'
      fields:
        - { name: Title }
    - name: "website-settings"
      label: "website settings"
      files:
        - label: "website settings"
          name: "site"
          file: "_date/site.yml"
          fields: 
              - label: "Heading"
                name: "heading"
                width: "string"
